### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by coderespawn** [kotsoft/FluidCinder#3]
Thanks for the amazing lib.  Could you please specify the license for this library?
I couldn't find it in the readme or the source headers

Thanks

**Comment by kotsoft** [comment]
I will look into this. I don't know too much about licensing but basically you can just use it any way you like.

**Comment by coderespawn** [comment]
Thanks! you rock.   (an MIT / BSD license has similar terms)

**Comment by kotsoft** [comment]
Sorry for addressing this so late. I got really busy with other things and kind of ignored my side projects for a while. I've added in the MIT license.

**Comment by coderespawn** [comment]
Thanks Grant
